---
title: "Tarea14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
use_python('~/anaconda3/envs/py38/bin/python')
```

```{python}
import numpy as np
import sympy as sp
```

1.
```{python}
u = np.array([-3,2,1,-2])
B = [(1,2,0,0), (-1,0,1,1), (0,0,-2,1), (-1,0,-1,0)]
MB = np.array(B).T
MB.dot(u)
```

```{python}
B1 = [(1,0,1,0), (1,0,0,-1), (0,1,0,-1), (0,1,-1,1)]

MB1 = sp.linalg.inv(np.array(B1).T)
MB1.dot(MB.dot(u))
```
2.

```{python}
u1 = np.array([3,2,-1])
u2 = np.array([4,1,1])
u3 = np.array([2,-1,1])
MBu = np.array([u1, u2, u3]).T
MBu
sp.linalg.matrix_rank(MBu) == MBu.shape[0]
sp.linalg.solve(MBu, (0,0,0))
```
El rango de $MB_u$ es igual al número de filas e igual al número de incognitas por lo tanto aplicando el teorema de Rouche-Frobenius obtenemos que es un SCD. Realizamos la resolución de este sistema de ecuaciones igualando a 0 y todas las incognitas son 0, por lo tanto se trata de 3 vectores LI y por ello podemos concluir que $B_u$ es una base de $\mathbb{R}_3$.

```{python}
v1, v2, v3 = MBv = sp.linalg.inv(MBu)
```
Las coordenadas de los vectores $v_1, v_2, v_3$ en la base $B_U$ son:
```{python}
v1
v2
v3
```

```{python}
x = np.array([1,2,3])
c = MBv.dot(x)
```
Utilizando $MB_v$ como matriz cambio de base podemos obtener que las cordenadas de $x$ en en la base $B_U$ son:
```{python}
c
```
3.
```{python}
v = (3,1,4)
B = [(1,-2,-1), (1,-1,0), (0,0,2)]
Pbc = np.array(B).T
PB = sp.linalg.inv(Pbc)
vB = PB.dot(v)
```

Las coordenadas del vector en base $\{(1, -2, -1),(1, -1, 0),(0, 0, 2)\}$ son:
```{python}
vB
```

4.
```{python}
u = (-3, 2, 1, -2)
B1 = [(1, 0, 0, -1),(0, 1, -1, 0),(0, 1, 0, -1),(0, 1, 1, 1)]
B2 = [(1, 2, 0, 0),(-1, 0, 1, 1),(0, 0, -2, 1),(-1, 0, -1, 0)]

PB1 = np.array(B1).T
PB2 = np.array(B2).T
ubc = PB2.dot(u)
ub1 = sp.linalg.inv(PB1).dot(ubc)
```

Las coordenadas en base $B_1$ son:
```{python}
ub1
```

5.
```{python}
v1 = (1, -2, 0, 3)
v2 = (2, -5, -3, 6)
v3 = (0, 1, 3, 0)
v4 = (2, -1, 4, -7)
v5 = (5, -8, 1, 2)

S1 = np.array([v1,v2,v3,v4,v5])
BS1 = sp.Matrix(S1).rref()
BS1
```
El rango es 3 de manera que solo los 3 primeros vectores son LI y por tanto la base la forman estos vectores:
```{python}
(v1, v2, v3)
```
6.

```{python}
F = [(1, 2, 1, 0),(0, 0, 1, 0),(1, 2, 0, 0)]
sp.Matrix(F).rref()
```
Una base del subespacio vectorial $F$ seria $\{(1, 2, 1, 0),(0, 0, 1, 0)\}$


7.
```{python}
S1 = [(1, -1, -1, 1),(1, -2, -2, 1),(0, 1, 1, 0)] 
S2 = [(1, 0, 0, 1),(0, -1, -1, 0)]

sp.Matrix(S1).rref()
```
Si calculamos la base de S1 encontramos que es $\{(1, 0, 0, 1),(0, -1, -1, 0)\}$ y a su vez igual a s2, por lo tanto deducimos que S1 esta formado por combinaciones lineales de S2.

8.

```{python}
v1 = (2, 1, 0, 3)
v2 = (3, -1, 5, 2)
v3 = (-1, 0, 2, 1)

sp.Matrix([v1,v2,v3]).rref()

```
La dimensión de E es 3

```{python}
A = sp.Matrix([v1,v2,v3]).T
b1 = sp.Matrix([1,1,1,1])
Ab1 = A.col_insert(A.cols, b1)
A.rank()
Ab1.rank()
```
El rango de la matriz A es inferior al rango de la matriz ampliada por lo que se trata de un sistema incompatible, con lo cual el vector (1,1,1,1) no pertence a E.

```{python}
b2 = sp.Matrix([2,3,-7,3])
Ab2 = A.col_insert(A.cols, b2)
Ab2.rank()
Ab2.rref()
```
Podemos comprobar que el vector (2,3,-7,3) si pertenece a E

9.

```{python}
A = [(1, 3, 2),(0, 3, 0),(2, 4, 5)]
B = [(0, 3, 1),(1, -3, 0),(-1, -4, 5)]
C = [(1, 3, -2),(-2, 0, 0),(-1, 0, 5)]
D = [(0, 3, 1, -1),(1, -3, 0, -2),(-1, -3, -4, 5),(-1, 0, 0, 0)]
E = [(1, 3, 0, 0),(0, -3, 0, -1),(1, 0, -3, 0),(1, 1, -1, 0)]

sp.Matrix(A).rank()
sp.Matrix(B).rank()
sp.Matrix(C).rank()
sp.Matrix(D).rank()
sp.Matrix(E).rank()
```
Todos los vectores son LI y la dimensión del subespacio vectorial generado por cada uno de los conjuntos es igual al rango de estos, es decir al número de vectores que componen cada uno de ellos.

10.

```{python}
x,y,z,t = u = (1,0,1,2)
x+y+z == 0
```
El vector u = (1, 0, 1, 2) no pertenece al subespacio H1

```{python}
H2 = [(1, 1, 1, 1),(1, 2, 3, 4)]
M = sp.Matrix(H2).T
M.col_insert(M.cols, sp.Matrix(u)).rref()
```
El vector u = (1, 0, 1, 2) no pertenece al subespacio H2

```{python}
a,b,g,d = sp.symbols('a b g d')
v = sp.Matrix([[a+b, a+g, g+d, a+d]])

# Obtenemos la base a partir de la base canónica de R4
Bp = sp.Matrix([
    v.subs({a:1, b:0, g:0, d:0}), 
    v.subs({a:0, b:1, g:0, d:0}), 
    v.subs({a:0, b:0, g:1, d:0}), 
    v.subs({a:0, b:0, g:0, d:1})])
B = Bp.row_insert(4, sp.Matrix([u])).T
B.rank()
```
El rango de B es 4 por tanto el vector u es LI con la base Bp y al ser el rango igual al rango del R4 podemos determinar que B es una base de R4

```{python}
B.rref()[0]
```
$$
\alpha = \frac{1}{2}\\\beta=\frac{1}{2}\\\gamma=-\frac{1}{2}\\\delta=\frac{3}{2}
$$

11.

```{python}
S1 = sp.Matrix([(2,-1,4,0), (0,-3,1,-5), (4,1,7,-5)])
S2 = sp.Matrix([(1,-1,0,6), (-1,0,3,1), (-1,0,2,1), (0,1,1,0)])

S1.rank()
S2.rank()

```

Todos son LI

12.

```{python}
a = sp.symbols('a', real=True)
M = sp.Matrix([(1 + a, 1, 1, 1),(1, 1 + a, 1, 1),(1, 1, 1 + a, 1),(1, 1, 1, 1 + a)])
sp.solve([M.det()], (a,))
```

El subespacio tendra dimensión inferior 4 cuando $\alpha$ valga -4 o 0. En caso contrario el subespacio que se genera coincide con $\mathbb{R}_4$

```{python}
M.replace(a, -4).rank()
M.replace(a, -4).rref()
```
En caso de $\alpha = -4$ la dimensión será 3, y la base del subespacio que generan será {(1, 0, 0, -1),(0, 1, 0, -1),(0, 0, 1, -1)}

```{python}
M.replace(a, 0).rank()
M.replace(a, 0).rref()
```
Para $\alpha = 0$ la dimensión sera 1 y la base del subespacio que generan será {(1,1,1,1)}

13.

```{python}
a,b,c,d,n = sp.symbols('a b c d n')
A = sp.Matrix([(1,2), (3,n)])
B = sp.Matrix([(a,b), (c,d)])
A @ B
```
```{python}
sp.solve([sp.Matrix([(1,0,2,0), (0,1,0,2), (3,0,n,0), (0,3,0,n)]).det()], (n,))
sp.solve((A @ B).replace(n, 6), (a,b,c,d))
sp.solve((A @ B), (a,b,c,d) )
```
Existen matrices cuadradas B tales que AB = 0 para $n=6$ con $b = -2\cdot d$ y $a=-2\cdot c$, y para $n\neq0$ con $a=b=c=d=0$ 

```{python}

A1 = A.subs({n: 6,})
B1 = B.subs({b: -2*d, a: -2*c})
B1.subs({d:0, c:0})
```


