  ---
  title: "tarea4"
  author: "Carlos Gálvez"
  date: "4/15/2020"
  output: html_document
  ---
  
  ```{r setup, include=FALSE}
  knitr::opts_chunk$set(echo = TRUE)
  knitr::opts_chunk$set(engine.path = list(octave = "/usr/bin/octave"))
  library(Biodem)
  
  ```
  
  
  1.
  ```{python}
  import numpy as np
  
  A = np.array([[0, 1, -2], [2, 3, -1], [1, -1, 5]])
  B = np.array([[1, -1, 2, 1], [2, -2, 2, -2], [-1, 2, 1, 2]])
  C = np.array([[2], [0], [1], [-4]])
  
  print(A.dot(B), '\n')
  print(B.dot(C), '\n')
  print(np.matrix.transpose(B), '\n')
  print(np.matrix.transpose(B).dot(A), '\n')
  print(np.matrix.transpose(C).dot(np.matrix.transpose(B)), '\n')
  ```
  
  2.
  
  ```{r}
  A = matrix(c(0,1,0,1), nrow = 2, ncol = 2)
  B = matrix(c(-1, -1, 0, 0), nrow = 2, ncol = 2)
  
  mtx.exp(A+B, 2) == mtx.exp(A, 2) + 2 * (A%*%B) + mtx.exp(B, 2)
  
  mtx.exp(A+B, 3) == mtx.exp(A, 3) + 3 * (mtx.exp(A,2) %*% B) + 3 * (A %*% mtx.exp(B, 2)) + mtx.exp(B, 3)
  ```
  
  3.
  
  ```{octave}
  A = [-1, 1, -2; 1, 1, 0; 2, 1, 1]
  rank(A)
  
  B = [-1, 2, 3, 4, 5; 1, 2, 1, 3, 2; 0, 4, 4, 7, 7]
  rank(B)
  ```
  4.
  ```{python}
  import numpy as np
  A = np.array([[1, 2, 0],[0, 1, -1], [0, 0, 0]])
  print(f'A:\n{A}')
  rank_A = np.linalg.matrix_rank(A)
  det_A = np.linalg.det(A)
  print(f'Determinant: {det_A}')
  print('La matriz no tiene inversa ya que su determinante es 0')
  ```
  
  $B^{-1} \Longleftrightarrow i \ne 0$ ya que de lo contrario $|B| = 0$
  ```{python}
  i = 0
  B = np.array([[i, 0, 0], [0, 0, 1], [1, i, 0]])
  print(f'B:\n{B}')
  det_B = np.linalg.det(B)
  print(f'Determinant: {det_B}')
  ```
  $i=1 \rightarrow$ 
  ```{python}
  i = 1
  B = np.array([[i, 0, 0], [0, 0, 1], [1, i, 0]])
  print(f'B:\n{B}')
  det_B = np.linalg.det(B)
  print(f'Determinant: {det_B}')
  print(f'Inversa:\n', np.linalg.inv(B))
  ```
  
